### PR TITLE
Initial roadmap/braindump of where I think we could go

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
// @GeertvanHorrik @laedit @gep13 @andreasohlund @simoncropp @dazinator @avanderhoorn @nikmd23

Input would be great

**Comment by gep13** [comment]
With regard to this: https://github.com/JakeGinnivan/Roadmap/blob/JakeGinnivan-patch-1/README.md#chocolatey-workflow are you referring to ChocolateyGUI?  Just wanted to check :-)

**Comment by JakeGinnivan** [comment]
@gep13 yep. If you want to document what you are doing, otherwise I can remove that section

**Comment by JakeGinnivan** [comment]
I probably should be clearer either way

**Comment by gep13** [comment]
In terms of Octopus Deploy, I believe I am right in saying the way that the Particular guys work (@simoncropp can confirm) they use a manual intervention step in the Octopus Workflow to verify the output of GitReleaseNotes, and make any changes.  Assuming everything is fine, they then allow the build to continue.  This to me seems like a common workflow, and something we would like to support.

**Comment by gep13** [comment]
> @JakeGinnivan said...
> @gep13 yep. If you want to document what you are doing, otherwise I can remove that section

Yip, I can expand on that section.

**Comment by gep13** [comment]
From my point of view, I would be happy to start utilising the output from GitReleaseNotes within GitHubReleaseManager, and I definitely think that GitHubReleaseManager and GitHubReleaseCreator should merge.  I don't think there is anything in GitHubReleaseCreator that isn't covered in GitHubReleaseManager, so I would vote for any additional work continuing in that tool to start with.  And then, as we discussed on Skype, start the creation of GitReleaseManager, which would be one tool to rule all the release targets, i.e YouTrack, GitHub, JIRA etc.

As we discussed, I had originally had thought that there would be GitHubReleaseManager, JiraReleaseManager, etc, i.e. one tools, with specific implementations for each target.  However, I am drawn to a single tool that knows how to work with all of them, but I do have a concern about the growing complexity of that type of tool, and the disparate ways that each of these release targets operate.

So, I guess what I am saying is, I am on the fence with regard to whether we should have one tool, or separate ones :-)

**Comment by JakeGinnivan** [comment]
I think that if we go the single tool road I think we will end up rolling GitReleaseNotes into GitReleaseManager

**Comment by gep13** [comment]
In terms of cross platform, personally, I would like to stick to C#, but that is simply because of where my core experience is.  We have already discussed with @nulltoken if it is possible to run libgit2sharp under mono, and the suggestion was that this could/should be possible, so given the work that has already gone into GitVersion, I would prefer to see us exhaust that route, before turning to anything else.

**Comment by gep13** [comment]
> @JakeGinnivan said...
> I think that if we go the single tool road I think we will end up rolling GitReleaseNotes into GitReleaseManager

Yes, that would make a lot of sense to me.

**Comment by JakeGinnivan** [comment]
Oh, I just remembered ~~the~~ _another_ tool that I wanted to build.

I want to create a build bot service which can listen for github pull requests, then post comments which can trigger builds. Much like https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin except it works with any build server.

**Comment by gep13** [comment]
And on the topic of a single org, yes, I think this is a great idea.  This means that we can have a central place to discuss the direction of all these tools, so that gets a big :+1: from me.

**Comment by JakeGinnivan** [comment]
Feel free to move GitHubReleaseManager across :)

**Comment by gep13** [comment]
> @JakeGinnivan said...
> Oh, I just remembered the tool that I wanted to build.
> I want to create a build bot service which can listen for github pull requests, then post comments which can trigger builds. Much like https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin except it works with any build server.

That sounds amazing! :-)

**Comment by gep13** [comment]
> @JakeGinnivan said...
> Feel free to move GitHubReleaseManager across :)

Sounds like a plan to me.  There are a couple pieces that I would need to update (i.e. coverity) as a result of moving the repo into a new org, but I can certainly bring that across.

**Comment by dazinator** [comment]
Would someone be able to point me to the GitHubReleaseManager repo? If it covers everything GithubReleaseCreator does then I'm happy to discontinue GithubReleaseCreator in favour of that! The main thing is whether it supports personal access token authentication with github.

**Comment by gep13** [comment]
You can find it under my github, gep13/githubreleasemanager.

I can say it doesn't support that, yet.

You can find the docs here: ghrm.readme.io.

Gary

Sent from my Windows Phone

**Comment by dazinator** [comment]
Cheers Gary, I'll take a look :)

My preference re gittools structure, would be to have a separation between tools that were purely git, and the sort of service provider level addon tools like github / gitbucket / jira etc etc.

For example gitreleasenotes and gitversion are pure git in my mind and perhaps belong together in a core / central architecture. GithubReleases / issue trackers and other sorts of bridges to third party services can probabky sit on top of that as separate tools..
Brain dump complete

**Comment by dazinator** [comment]
For example something like:

GitTools.Common -- contains everything purely git based no services.
GitTools.Jira 
GitTools.GitHub

Etc etc. GitTools.Common could be referenced by all utilities to expose release notes / git version etc etc.

**Comment by dazinator** [comment]
..although I do also like the idea of "one tool to rule them all" haha

**Comment by laedit** [comment]
Excellent idea!

But even if I like the idea of a common org, I must question the place of SemanticReleaseNotes and SemanticReleaseNotesParser because they are not related to Git.

Otherwise, the idea of "one tool" is seducing but I think that a tool for each task is preferable because they can be used by anyone even if they don't follow one of the supported workflows.

And if you have any feedback regarding the use of SemanticReleaseNotes I'm glad to hear it. :smiley:

**Comment by JakeGinnivan** [comment]
> But even if I like the idea of a common org, I must question the place of SemanticReleaseNotes and SemanticReleaseNotesParser because they are not related to Git.

Agreed, the reason I list them is not to bring those project into this org, but to use them in the other tools. I like the idea of all the GitTools using a parsing library rather than doing it themselves. I also think we should use semantic release notes as the input/output format rather than inventing our own.

**Comment by gep13** [comment]
> @dazinator said...
> The main thing is whether it supports personal access token authentication with github.

Actually, I clearly wasn't thinking last night when I replied :-)  I currently use a Personal Access Token when connecting to GitHub, and it worked fine.  The access token is put in with the `-p` parameter, and it works as expected.

**Comment by JakeGinnivan** [comment]
> @dazinator My preference re gittools structure, would be to have a separation between tools that were purely git, and the sort of service provider level addon tools like github / gitbucket / jira etc etc.
> For example gitreleasenotes and gitversion are pure git in my mind and perhaps belong together in a core / central architecture. GithubReleases / issue trackers and other sorts of bridges to third party services can probabky sit on top of that as separate tools..

GitVersion I completely agree, with GitReleaseNotes we could have a core library with a simple exe which only gets issues from commits to generate the release notes and writes to a markdown file. As soon as you move away from simple commits/markdown file then you are talking with some service provider.

> @laedit Otherwise, the idea of "one tool" is seducing but I think that a tool for each task is preferable because they can be used by anyone even if they don't follow one of the supported workflows.

If we lay out the workflows people use, I am sure we could come up with a decent command line tool which supports it all. The advantage of a single tool is the deployment/versioning/build/release/install process is only done once no matter what you are using

Having separate tools seem more like something which will end up getting in the way as you will need to write out to a markdown file then read that from a different tool to do the same build.

**Comment by dazinator** [comment]
@JakeGinnivan  - here's what I am thinking - is this what you have in mind - something like this: https://github.com/GitTools/Roadmap/wiki/The-Great-Git-Grand-Unification-Theory-%231

**Comment by laedit** [comment]
@JakeGinnivan Ok so now I'm good with the one tool. :smiley: 

Concerning the cross-platform, like @gep13 I'm more comfortable with sticking to C# and have some build/tests under Mono.

**Comment by JakeGinnivan** [comment]
xplat is more long term, try and bring other communities in once we have the problem solved and working for us

**Comment by JakeGinnivan** [comment]
Ok, seems we have a little bit of initial consensus so I have updated the PR to link to the wiki for the tools list. Now people can contribute their own workflows and fix anything

**Comment by JakeGinnivan** [comment]
@dazinator as for the unification theory questions (maybe turn into a PR to make for easy collaboration) 

> Release Notes Formatters (Markdown, JSON, Html etc)
> This would stay in the semantic release notes related tools, we would just operate on the semantic release notes format itself.
> 
> Unclear where the following tools would fit into this sort of unification as I am not familiar with them at present:
> GitLink is completely separate, but it is a useful tool and related to releasing your software. it would stay separate though

The API Approval stuff is to have a diff of the public API changes, useful for breaking changes but also useful for minor bumps which add new features. This would not be part of the GitReleaseManager or whatever we call it, but the tools could live in this org and we can have documentation how to build that into your releases. If there is demand we could add it as a feature but then I think we are conflating too much together?

**Comment by gep13** [comment]
I have added some information about the ChocolateyGUI way of doing things.

**Comment by gep13** [comment]
> @JakeGinnivan said...
> If there is demand we could add it as a feature but then I think we are conflating too much together?

Yes, I agree, I think that would be a step too far.

**Comment by GeertvanHorrik** [comment]
I think we should split up tools by feature, not by provider or try to merge them all.

1) GitVersion => determine the version, separate step in the build / publish process
2) GitLink => source indexing, separate step after build has been completed
3) GitReleaseNotes => create release notes based on the repository + issue tracker
4) GitRelease(Manager) => create / release a version (no matter what issue tracker we use)

I think we can greatly benefit from having a GitTools.Core that has support for dynamic repositories so we can easily add this feature to every tool (we have this implemented separately in every tool now). The we can have GitTools.IssueTrackers.Jira, GitTools.IssueTrackers.GitHub, etc. We can also have GitTools.SourceHosting.GitHub, GitTools.SourceHosting.BitBucket, etc.

I think once we have the core components (all API assemblies can be embedded by using Costura), we have a nice set of shared components making it much easier for us to improve all the tools at once for a specific provider.

I think we should focus on windows for now (isn't that what we all use?). I know xplat is really cool and such, but let's make it work for ourselves first. Then if and when people pick it up, we can decide what to do with it.

I think all people involved in this thread are after the same goal: try to automate as much of the build / release management cycle as possible without user interventions. Let's focus on that instead of serving others with xplat.

**Comment by GeertvanHorrik** [comment]
And maybe we should start with Gitter. Not for everything (it's not a good tool to keep track of history), but for short discussions it's great. Then we can put the summaries up here as issues.

**Comment by GeertvanHorrik** [comment]
See https://gitter.im/GitTools/General 

It's public, I have added everyone that was involved in this discussion.

**Comment by JakeGinnivan** [comment]
1 and 2, definite different tools. 3 & 4, maybe not.
The issue is intermediate storage for a few workflows, I don't want to checkin releasenotes.md when using GitHub releases because of multiple tools.

I love the core idea with dynamic repos, it also can have libgit2sharp extension method which are not good for core but useful for our tools. I was also thinking it could abstract git for our uses and then we could call GitHub git apis to get history etc instead of cloning.  We would fall back to cloning for any hosts which don't have those apis That would save heaps of traffic for GitHub?

Sent from my Windows Phone

**Comment by dazinator** [comment]
RE GitRepo abstraction - in GitReleaseNotes - I took a lot of the work from GitVersion and created a `GitRepoContext` class in GitReleaseNotes which wraps the underlying repo - and adds additional methods, and also stores some additional commonly needed state like credentials etc - to save passing those arguments in all susequent method calls when working with the repo. I found this beneficial. I'd urge you to use this code for working with a GitRepo if possible over the GitVersion code.. but entirely up to you guys.

**Comment by dazinator** [comment]
- Recommend we take @GeertvanHorrik lead and use Gitter for further discussion - as allready starting to talk about these ideas in 2 places now :)

**Comment by JakeGinnivan** [comment]
> RE GitRepo abstraction - in GitReleaseNotes - I took a lot of the work from GitVersion and created a GitRepoContext class in GitReleaseNotes which wraps the underlying repo - and adds additional methods, and also stores some additional commonly needed state like credentials etc - to save passing those arguments in all susequent method calls when working with the repo. I found this beneficial. I'd urge you to use this code for working with a GitRepo if possible over the GitVersion code.. but entirely up to you guys.

@GeertvanHorrik where did you take the code for GitTools.Core from, did you see @dazinator's message here?

**Comment by GeertvanHorrik** [comment]
I just used GitTools as a basis (wanted to test if everything worked ok), happy to use any other code. Will look into @dazinator code, or he is free to replace what we have in GitTools.Core.

**Comment by dazinator** [comment]
No biggie, i'll raise an issue in GitTools.Core to discuss any proposed changes, before I repeat / attempt any work. Atleast we have a base point now.

**Pull request merged**
